# Generated by Django 4.0.4 on 2022-05-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cuser_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
